name: CD Java App
on:
    push:
        branches:
            - main
jobs:
    deploy_app:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
              
            -   name: Build and push
                uses: docker/build-push-action@v6
                with:
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/java-app1:latest
            
            -   name: Configure AWS Credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: ${{ secrets.AWS_REGION }}
            
            -   name: Deploy to K8s
                run: aws eks update-kubeconfig ${{ secrets.AWS_REGION }} --name eks-cluster

            -   name: Deploy to Kubernetes
                run: kubectl apply -f ./k8s/deployment.yaml --context arn:aws:eks:${{ secrets.AWS_REGION }}:xxxxxxx:cluster/eks-cluster 
        
                    

