name: CI Java App1
on:
    schedule:
        - cron: "*/1 * * * *"
          
           
jobs:
    build:
        name: Build and Package Java App
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Build and Packagen
              run: mvn clean package

   
